# Generated by Django 2.2 on 2019-04-01 20:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page', models.TextField(default='Please Fill')),
                ('description', models.TextField(default='Please Fill')),
                ('location', models.CharField(default='', max_length=100)),
                ('startdate', models.DateField(default=datetime.datetime.today)),
                ('enddate', models.DateField(default=datetime.datetime.today)),
                ('starttime', models.TimeField(default=datetime.time(12, 40, 32, 182957))),
                ('endtime', models.TimeField(default=datetime.time(12, 40, 32, 182983))),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Please Fill')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privledge', models.PositiveIntegerField(default=0)),
                ('orgID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgAdminPanel.Organization')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('personelMax', models.PositiveIntegerField(default=1)),
                ('personel', models.PositiveIntegerField(default=0)),
                ('startdate', models.DateField(default=datetime.datetime.today)),
                ('enddate', models.DateField(default=datetime.datetime.today)),
                ('starttime', models.TimeField(default=datetime.time(12, 40, 32, 186246))),
                ('endtime', models.TimeField(default=datetime.time(12, 40, 32, 186264))),
                ('description', models.TextField(default='Please Fill')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgAdminPanel.Event')),
                ('userID', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventVol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('eventID', models.ManyToManyField(to='orgAdminPanel.Event')),
                ('userID', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='orgID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgAdminPanel.Organization'),
        ),
    ]
