# Generated by Django 2.2b1 on 2019-03-01 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgAdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Please Fill')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='Please Fill'),
        ),
        migrations.AddField(
            model_name='event',
            name='enddate',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
        ),
        migrations.AddField(
            model_name='event',
            name='personelMax',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='startdate',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='personel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrganizationUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privledge', models.PositiveIntegerField(default=0)),
                ('orgID', models.ManyToManyField(to='orgAdminPanel.Organization')),
                ('userID', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventVol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('eventID', models.ManyToManyField(to='orgAdminPanel.Event')),
                ('userID', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='orgID',
            field=models.ManyToManyField(to='orgAdminPanel.Organization'),
        ),
    ]
