# Generated by Django 2.2b1 on 2019-03-06 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdminPanel', '0003_auto_20190301_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='orgID',
        ),
        migrations.AddField(
            model_name='event',
            name='orgID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgAdminPanel.Organization'),
        ),
    ]
