# Generated by Django 2.2b1 on 2019-03-06 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdminPanel', '0004_auto_20190305_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='orgID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgAdminPanel.Organization'),
        ),
    ]
