# Generated by Django 2.2b1 on 2019-03-06 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgAdminPanel', '0005_auto_20190306_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationusers',
            name='orgID',
        ),
        migrations.AddField(
            model_name='organizationusers',
            name='orgID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgAdminPanel.Organization'),
        ),
        migrations.RemoveField(
            model_name='organizationusers',
            name='userID',
        ),
        migrations.AddField(
            model_name='organizationusers',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
