# Generated by Django 2.2b1 on 2019-03-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdminPanel', '0005_auto_20190305_1913'),
        ('orgAdminPanel', '0006_auto_20190306_1203'),
    ]

    operations = [
    ]
