# Generated by Django 2.2b1 on 2019-03-27 01:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgAdminPanel', '0007_merge_20190307_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='personel',
        ),
        migrations.RemoveField(
            model_name='event',
            name='personelMax',
        ),
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.TimeField(default=datetime.time(17, 15, 39, 741676)),
        ),
        migrations.AddField(
            model_name='event',
            name='page',
            field=models.TextField(default='Please Fill'),
        ),
        migrations.AddField(
            model_name='event',
            name='starttime',
            field=models.TimeField(default=datetime.time(17, 15, 39, 741640)),
        ),
        migrations.AlterField(
            model_name='event',
            name='enddate',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='startdate',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('personelMax', models.PositiveIntegerField(default=1)),
                ('personel', models.PositiveIntegerField(default=0)),
                ('startdate', models.DateField(default=datetime.datetime.today)),
                ('enddate', models.DateField(default=datetime.datetime.today)),
                ('starttime', models.TimeField(default=datetime.time(17, 15, 39, 746050))),
                ('endtime', models.TimeField(default=datetime.time(17, 15, 39, 746078))),
                ('description', models.TextField(default='Please Fill')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgAdminPanel.Event')),
                ('userID', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
