# Generated by Django 2.2b1 on 2019-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('volMax', models.IntegerField()),
                ('volCurrent', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
