# Generated by Django 2.2b1 on 2019-03-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='domain_name',
        ),
    ]
