# Generated by Django 2.1.7 on 2019-04-17 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedOrganizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='What is the reason for the report?')),
            ],
        ),
        migrations.CreateModel(
            name='ReportedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='What is the reason for the report?')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_org_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportedusers',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportedorganizations',
            name='orgID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='certs',
            field=models.ManyToManyField(to='createAccount.Certs'),
        ),
    ]
