# Generated by Django 2.2b1 on 2019-03-05 03:09

import createAccount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createAccount', '0003_auto_20190304_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.CharField(default="Hi, I'm a volunteer.", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(default='thispersondoesnotexist.jpg', null=True, upload_to=createAccount.models.MyUser.save_usr_pic),
        ),
    ]
